Retry ubuntu-toolchain-r-test apt source setup
In 614c90fe21cf1d9cf6fb18684187d8c7e2f61de6, I assumed
apt-add-repository has been stable recently, but I saw PR randomly
failed for it today.

This commit only deals with "ubuntu-toolchain-r-test" and does NOT deal
with `llvm-toolchain-xenial-8` intentionally, because what it does
(mainly curl from build.travis-ci.org) seems to be more reliable than
"ubuntu-toolchain-r-test". Also `&clang-8` jobs are basically
allow_failures and it's less important to be stabilized.

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -82,14 +82,17 @@ env:
 
   - &gcc-8
     compiler: gcc-8
-    addons:
-      apt:
-        config:
-          retries: true
-        sources:
-          - ubuntu-toolchain-r-test
-        # `packages` are installed in `before_install` for retries.
+    # # Not using addon to control retries
+    # addons:
+    #   apt:
+    #     sources:
+    #       - ubuntu-toolchain-r-test
     before_install:
+      - |-
+        for seconds in 1 25 100 -1; do
+          sudo -E apt-add-repository -y "ppa:ubuntu-toolchain-r/test"
+          if [[ $? = 0 ]]; then break; else sleep "$seconds" || exit 1; fi
+        done
       - |-
         for seconds in 1 25 100 -1; do
           travis_apt_get_update
@@ -279,14 +282,17 @@ env:
       - GCC_FLAGS=-m32
       - debugflags=-g0
       - SETARCH='setarch i686 --verbose --3gb'
-    addons:
-      apt:
-        config:
-          retries: true
-        sources:
-          - ubuntu-toolchain-r-test
-        # `packages` are installed in `before_install` for retries.
+    # # Not using addon to control retries
+    # addons:
+    #   apt:
+    #     sources:
+    #       - ubuntu-toolchain-r-test
     before_install:
+      - |-
+        for seconds in 1 25 100 -1; do
+          sudo -E apt-add-repository -y "ppa:ubuntu-toolchain-r/test"
+          if [[ $? = 0 ]]; then break; else sleep "$seconds" || exit 1; fi
+        done
       - |-
         for seconds in 1 25 100 -1; do
           travis_apt_get_update
