Add debug print for random CI failure on osx Travis
git-svn-id: svn+ssh://ci.ruby-lang.org/ruby/trunk@67347 b2dd03c8-39d4-4d8f-98ff-823fe69b080e

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -357,7 +357,20 @@ before_script:
   - rm -rf ~/config_2nd
   - mv ../config_2nd ~
   - chmod u-w ..
-  - $SETARCH make -s $JOBS && make install
+  - |-
+    if ! $SETARCH make -s $JOBS; then
+      if [ "$(uname)" = Darwin ]; then
+        # Debugging "Permission defined" failure on darwin like https://travis-ci.org/ruby/ruby/jobs/508683759
+        set -x
+        echo $USER
+        ls -la
+        ls -la .ext
+        ls -la .ext/common
+        ls -la .ext/common/bigdecimal
+      fi
+      exit 1
+    fi
+  - make install
   - ccache --show-stats
   - |-
     [ -z "${GEMS_FOR_TEST}" ] ||
