* configure.in: ignored working directory same as prefix value.   [ruby-core:54999] [Bug #8409]
git-svn-id: svn+ssh://ci.ruby-lang.org/ruby/trunk@47151 b2dd03c8-39d4-4d8f-98ff-823fe69b080e

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -229,6 +229,10 @@ test -z "$CXX" || ac_cv_prog_CXX="$CXX"
 if test "$program_prefix" = NONE; then
   program_prefix=
 fi
+if test "$prefix" = `pwd`; then
+  echo "--prefix cannot be the current working directory."
+  exit 1;
+fi
 RUBY_BASE_NAME=`echo ruby | sed "$program_transform_name"`
 RUBYW_BASE_NAME=`echo rubyw | sed "$program_transform_name"`
 AC_SUBST(RUBY_BASE_NAME)
