Partially allow failures in test-bundled-gems
Tests of minitest randomly fails with strange errors:
https://dev.azure.com/rubylang/ruby/_build/results?buildId=303
https://dev.azure.com/rubylang/ruby/_build/results?buildId=314

Instead of marking `continueOnError` for all, let me select
failure-allowed gems individually.

git-svn-id: svn+ssh://ci.ruby-lang.org/ruby/trunk@67428 b2dd03c8-39d4-4d8f-98ff-823fe69b080e

diff --git a/Makefile.in b/Makefile.in
--- a/Makefile.in
+++ b/Makefile.in
@@ -529,10 +529,17 @@ enc/encinit.$(OBJEXT): enc/encinit.c $(SETUP)
 
 cont.$(OBJEXT): $(COROUTINE_H)
 
+# Override this to allow failure of specific gems on CI
+TEST_BUNDLED_GEMS_ALLOW_FAILURES =
+
 test-bundled-gems-run:
 	$(Q) set -e; while read gem _; do \
-	  echo testing $$gem gem && \
-	  $(XRUBY) -C $(srcdir)/gems/src/$$gem -Ilib ../../../.bundle/bin/rake; \
+	  echo testing $$gem gem; \
+	  if echo $(TEST_BUNDLED_GEMS_ALLOW_FAILURES) | grep -q $$gem; then \
+	    $(XRUBY) -C $(srcdir)/gems/src/$$gem -Ilib ../../../.bundle/bin/rake || true; \
+	  else \
+	    $(XRUBY) -C $(srcdir)/gems/src/$$gem -Ilib ../../../.bundle/bin/rake; \
+	  fi; \
 	done < $(srcdir)/gems/bundled_gems
 
 update-src::
