CI: Add make-ibm job in ubuntu.yml and remove ubuntu-ibm.yml
Add `make-ibm` job to run ppc64le/s390x cases in the `ubuntu.yml`, and remove
`ubuntu-ibm.yml`. This commit improves removing a duplicated logic between the
`ubuntu.yml` and `ubuntu-ibm.yml`.

I am using the YAML anchors and aliases feature to avoid the duplicated logic.
The document is below.

https://docs.github.com/en/actions/reference/workflows-and-actions/reusing-workflow-configurations#yaml-anchors-and-aliases

I don't add the `make-ibm` job to the `result` job, the line `needs: [make]`
intentionally to make the `make-ibm` job's result optional to merge PRs.

diff --git a/.github/workflows/ubuntu.yml b/.github/workflows/ubuntu.yml
--- a/.github/workflows/ubuntu.yml
+++ b/.github/workflows/ubuntu.yml
@@ -45,7 +45,7 @@ jobs:
             extra_checks: [capi]
       fail-fast: false
 
-    env:
+    env: &make-env
       GITPULLOPTIONS: --no-tags origin ${{ github.ref }}
       RUBY_DEBUG: ci
 
@@ -59,7 +59,7 @@ jobs:
       || (github.event_name == 'push' && github.event.pull_request.user.login == 'dependabot[bot]')
       )}}
 
-    steps:
+    steps: &make-steps
       - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
         with:
           sparse-checkout-cone-mode: false
@@ -73,7 +73,19 @@ jobs:
         with:
           ruby-version: '3.1'
           bundler: none
-        if: ${{ !endsWith(matrix.os, 'arm') }}
+        if: >-
+          ${{ !endsWith(matrix.os, 'arm')
+          && !endsWith(matrix.os, 'ppc64le') && !endsWith(matrix.os, 's390x') }}
+
+      # A temporary workaround: Set HOME env to pass the step
+      # ./.github/actions/setup/directories.
+      # https://github.com/IBM/actionspz/issues/30
+      - name: Set HOME env
+        run: |
+          echo "HOME: ${HOME}"
+          echo "HOME=$(ls -d ~)" >> $GITHUB_ENV
+        working-directory:
+        if: ${{ endsWith(matrix.os, 'ppc64le') || endsWith(matrix.os, 's390x') }}
 
       - uses: ./.github/actions/setup/directories
         with:
@@ -123,6 +135,21 @@ jobs:
         continue-on-error: true
         timeout-minutes: 3
 
+      # Avoid possible test failures with the zlib applying the following patch
+      # on s390x CPU architecture.
+      # https://github.com/madler/zlib/pull/410
+      - name: Disable DFLTCC
+        run: echo "DFLTCC=0" >> $GITHUB_ENV
+        if: ${{ endsWith(matrix.os, 's390x') }}
+
+      # A temporary workaround: Set the user's primary group to avoid a mismatch
+      # between the group IDs of "id -g" and C function getpwuid(uid_t uid)
+      # pw_gid.
+      # https://github.com/IBM/actionspz/issues/31
+      - name: Set user's group id
+        run: sudo usermod -g "$(id -g)" runner
+        if: ${{ endsWith(matrix.os, 'ppc64le') || endsWith(matrix.os, 's390x') }}
+
       - name: make ${{ matrix.test_task }}
         run: |
           test -n "${LAUNCHABLE_STDOUT}" && exec 1> >(tee "${LAUNCHABLE_STDOUT}")
@@ -167,6 +194,31 @@ jobs:
           label: ${{ matrix.test_task }} ${{ matrix.configure }}${{ matrix.arch }}
           SLACK_WEBHOOK_URL: ${{ secrets.SIMPLER_ALERTS_URL }} # ruby-lang slack: ruby/simpler-alerts-bot
         if: ${{ failure() }}
+
+  make-ibm:
+    strategy:
+      matrix:
+        include:
+          - test_task: check
+            os: ubuntu-24.04-ppc64le
+          - test_task: check
+            os: ubuntu-24.04-s390x
+      fail-fast: false
+
+    env: *make-env
+
+    runs-on: ${{ matrix.os }}
+
+    if: >-
+      ${{github.repository == 'ruby/ruby'
+      && !(false
+      || contains(github.event.head_commit.message, '[DOC]')
+      || contains(github.event.pull_request.title, '[DOC]')
+      || contains(github.event.pull_request.labels.*.name, 'Documentation')
+      || (github.event_name == 'push' && github.event.pull_request.user.login == 'dependabot[bot]')
+      )}}
+
+    steps: *make-steps
 
   result:
     if: ${{ always() }}
